source 'https://rubygems.org'
ruby '2.2.0'

# gem 'roda', '2.0.0'
gem 'roda', :git => 'git://github.com/jeremyevans/roda.git'
gem 'rack'

gem 'puma'
gem 'foreman'

gem 'tilt'

gem 'shotgun'
gem 'rspec'
gem 'capistrano', '~> 3.3.0'
